language: python
python:
- 3.6
services:
- docker
cache: pip
install:
- pip install pytest
- pip install -r requirements.txt
script:
- PYTHONPATH=`pwd` pytest
after_success:
- docker login -u=${DOCKER_USERNAME} -p=${DOCKER_PASSWORD} &&
  docker pull ${DOCKER_USERNAME}/rsd-backend &&
  docker build -t ${DOCKER_USERNAME}/rsd-backend --cache-from ${DOCKER_USERNAME}/rsd-backend . &&
  docker push ${DOCKER_USERNAME}/rsd-backend
env:
  global:
  - COMMIT=${TRAVIS_COMMIT::8}
  - secure: rXMwvdIAP6bzRYScj1GV6csDe9UVrBWenVJNa5OoiRseeLIGaHjrDkxjL6GfEUAsQNwJDZsU1D1WVOMlEehCn8uTK4DHaF/XUpTSrV9ZsuM4Tnuf5HBuPSUSX//mqZsYUMvgxH6DajJp4hxeAp8NCEQfhpiYd250jIlh5+YwBTWq5vTjotdzanWNs4YQ0p6F8gNhr85dXwpeWqW/m5pUgdQfUl6D3TS1ZF3DonU96KY5+qHUn+fVWxeUcCeeSH1INGG9ywmY08BCWSAzL9o7t1jLdaalEZuVkMSohUamLrS+2g4i3ZGxBJNKYXN0CGMRfhsG2ZUJnRzFtqxU8yvnpHt8jKKtk3pZ0xbTQPNtmYHeGzjfbMmGDAOBG6EJyQl9TFXjy9G8OePsWLjpt7PPiRpAYgVGLanzHAo0g1OuXwu8uDxplT9dtPDvnKK3HnyXJa9oFvBYlKkKjftEXy2mHwLMjjAT73M2N1K1VimogBm9oZnYK/pSFVnttfnZd2mNnBARw9hntmvyOz5DVf+Hjm4uiixhlt4YF/4FpIgLKWs70X7T/VkDojXi+aolrl6i+9eUOacwn6vC0RjHCOoig0JAQEfJomoLqXUB2YmI5ShAQ0Z+UwaG8RUJBbh8NC+uGrXoeQoaulaIJgrpSqN8aD4edFm0uEZNczReymPrkk0=
  - secure: knoC/wivq7nsn55TvM5xa+g7F5HS6JVVoK5AZjL5yIaiKEbINFPkCW7P2Y8tuKU77bf/MLJoB3iSzz942WSWT9ks+i+inP0FeZs8XbmsaORfe4kdwPwBwPr+kd8tSmQoI91PxfnAfpZvLOZCccOfh3jAfzXWwgLtgmqlsD0dWPtmm3x2PwYNWVqkA3vUz8evHPljnldYEtWrROo43tioQ70ETjbKniAndSRc/WC+hTC/oFeaH+MzwwR5siWM2KMqZtIVJsoXv0P35NOaVOAERRfdz+/TD0uuJjneeehL7r816eqU8wlB6TkMxwiHukoCd2M0ovd4yakUVJTO+42nDATcIuWwXj3omsxBzKCE2PvTqXmYrjNC47qII6bFIvMkNhx9n6sVXcvIyt3pINxhCzj9BtfQhFZMBXWdYCfaKecw1smSowEPWT+5BhqQDjnBX7A3SjihOvahWlITwA0/OtfTMbWUV5Jxj84i3uOfmcAxvKniMvuQjhCBdiYeW2Jj65PeVPwgdyXI1WV5wKshYRgogeWBDx9W2NEuKLywl7SqNdbjsI2l2yyy7ePMd7MiGK431J1Ce88ssgSTftAoPZoc9gasPKHPe6zdaRm8z+qkg1d3VSRvdwaH9vgSPu0kDjMvHL5Sf6E7A4OmeuZB9XfCg8/5cU1ibPhQmDMInWI=
