language: node_js
node_js:
  - "8"
cache:
  directories:
    - node_modules
install:
  - yarn
script:
  - yarn test
  - yarn build
after_script:
  - curl -L -X POST https://registry.hub.docker.com/u/rsdnlesc/admin/trigger/4cca74d7-eb82-4b1f-aee2-0db404088049