language: node_js
node_js:
  - "8"
cache:
  directories:
    - node_modules
before_install:
  - >-
    openssl aes-256-cbc 
    -K $encrypted_xxxxxxxxxxxx_key 
    -iv $encrypted_xxxxxxxxxxxx_iv 
    -in github_deploy_key.enc 
    -out github_deploy_key 
    -d
  - chmod 600 github_deploy_key
  - eval $(ssh-agent -s)
  - ssh-add github_deploy_key
install:
  - yarn
script:
  - yarn test && yarn build
after_success:
  - if [[ $TRAVIS_BRANCH == 'master' ]]; then
    curl -L -X POST https://registry.hub.docker.com/u/rsdnlesc/admin/trigger/$DOCKERHUB_TRIGGER_TOKEN;
    fi
