language: node_js
node_js:
  - "8"
cache:
  directories:
    - node_modules
install:
  - yarn
script:
  - yarn test && yarn build
after_success:
  - if [[ $TRAVIS_BRANCH == 'master' ]]; then
    curl -L -X POST https://registry.hub.docker.com/u/rsdnlesc/admin/trigger/$DOCKERHUB_TRIGGER_TOKEN;
    fi
