language: python
python:
  - 3.6
services:
  - docker
cache: pip
install:
  - pip install pytest
  - pip install -r requirements.txt
script:
  - PYTHONPATH=`pwd` pytest
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" &&
    docker build -t rsd-backend . &&
    docker push tommos0/rsd-backend
env:
  global:
    - COMMIT=${TRAVIS_COMMIT::8}
    - secure: "T8W5Z7qYXnBv9oPvMD1s0kCGL+8K0ZNlJQQrsPXnRWAkXtw7BX44GO76KVmPyC1EcWfQXjLT3dA4ccY0mCetaMyYQYqHcaTZ8LNdjLN7PSelkzFMCAOfB0Gg40uZ4z7fDSQIy9oJ6R7FdtXgcKwkb/7MJCEEqP8L9SLBIaUWW/raKhdSfrTW9wP6sPm1BlHGNHgMAv4YOi4SUHMgco+fPjAFz1JnKeZLCMnUinXUwwZX7cTv1aCYXyhD3TVhMx7NMMPP2SF1IBTj1iMtXwElj/4H2I1ZfcDJpP6xVo/fcHUl4i0toTOERIr/2UKB4JeB0kjM9xWkJAb3RMEjvTMVIyI3cX/hovC2wPs3Dva8a8HAvux50cGBbQ9JTPOtbi4EWyDOa+53C5UuTK8jap2ClOToONCJe9dKehunkcmyN4Db4Ulr43b0kj2NRG2s/O49M2qPQHJ5mIZqFK3dW9LxXLLCmGsxb1Movbdtfo9+t3U6SnZf3GxdJTTsRvMrLtAYFWukOXSeoZ8DpairOdydsy5b4dlGXQiOmd5SuZXQG9mz8L1nGN9x/qjf1lA+ZDKCjZC4BsD46NZjAManCC95eye46id0Gbx2SP/Uuqgtg84rV4NCpCOENGptqkHLKrU6BxKuOAiYY8NTuAOWJGr4qPdorX3xBsoXLKEXajUwUe4="
    - secure: "x8f/HbIGqjNYn32Cga1iqcCI8yWv1kMCFZ47C1aUy7UzjB8rFzrGg11tVHVlgz3R74gkZU+lpvm/97pPrumJKvnwMq4Lej60S2aQwwDPxSjY18Y/CG6U32A7yFX81No7/4L3A54offeM0F/ZJqr1uKMjRl0aSXR7U8+fKqzeANbe0yOxlGCQCQSed0Ft4OxBM4j0yBE//nPKSfV2jZZZ2rdK+VhKHwjWfCQBybuYpvAsyNuQsdqAz+DzolCQJMCNAsprYKt5d3/zZOhIu6ugG2nKiHJk8gag4pMqMV1Jx3jVQ0swBPSAR5eNCrkUqxJsL5oXk1WhdM6h4eK0JfBkqNjZMPcIWcObnTRMEmNtxp+eb0F8FibRC/fx4ocwsob5CGWuM+D87EYcN0Uy7ofNfj5T9lFW3PC2eIKNcVo5G4SsWb8Zwqd4Kfl9dMVIaVfqKXrPM0igmZKGqTMIQmn1ssiC77LV7qKB0tmQTde/wyW1edQ1X7ben8pb9I46A7URsBcgHhw3OWXJiESjss02rMqr4aInS1DGnOv6FHkolFd8TioXcDpPaqx4ijEQzKADGUac+/hhPHPgOO2qg/GO1twGG8ZGsWM022tQRouoVyMt6bUjomX+ML+/6oMDKLeElDkoy5bXlpPn2WIqIkG/whn1gjEa8XRTvY8smKoKYAU="