language: python
python:
  - 3.6
services:
  - docker
cache: pip
install:
  - pip install pytest
  - pip install -r requirements.txt
script:
  - PYTHONPATH=`pwd` pytest
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker build -t rsd-backend .
  - docker push tommos0/rsd-backend
env:
  global:
    - COMMIT=${TRAVIS_COMMIT::8}
    - secure: "sAHC58bsWbCbLpxx4WfXw7S9aX0vzrh5PCuU8jQ835rffghBD1OzaZ3TsKiqCrkhTYCHrjXLJvlwNGe2+1R8Z+sgfP1I+WNrUx+ZUhKbj8KMOGEXhndFUplh7lRvqB3snmaG28f52Y6F5vx/iurnvUo2C1vrBiahXdIEmsUMOtDY4RLPpoTepw+X+s+KFPuBtY0g+jYBfdmi8k2wQila6WRnyp5/RLR2wK1EhSrkoNhSromLbwUg3ZYICgp+A9v7ppW3DNWB4Cp2Vgzj3icXlGdM19TR8Rb3dfK7lBu2uQdYl6fCDOGbetbYuLnjC4u1e3Oj5jlJ1A8/6B7Gs4vCAGiLqFoo5nTPApJi0FnllT0s50x18wQ8H1TEMFDAv1jgdlEqTAaRy+kyRZu2LzRnSLj/gBPmo2oRZZbWTyKPELLY6+6nKqdXVeS/XKhjDqEnlaT4zO3/qWdAqbKAdtBmZwgvtnuSU7IPBYPBT+gFNlak9+VEqizNr9qrcjENhUbprhNuyBzztOsN83sbZouiFNs91rzaegMW3+rl21sIagftcrIr91RCgEN80zgNi1F0nAT1Lz3lGqNdDPjwoB8rHRaqW7UKdWhN5qCIjAaBwHkgsucHSVVxNJX4Sbb895wxzyTQzq4m5j7DX01ESFqUE36Xy9AzLf9aY7KCnPOUkmU="
    - secure: "x8f/HbIGqjNYn32Cga1iqcCI8yWv1kMCFZ47C1aUy7UzjB8rFzrGg11tVHVlgz3R74gkZU+lpvm/97pPrumJKvnwMq4Lej60S2aQwwDPxSjY18Y/CG6U32A7yFX81No7/4L3A54offeM0F/ZJqr1uKMjRl0aSXR7U8+fKqzeANbe0yOxlGCQCQSed0Ft4OxBM4j0yBE//nPKSfV2jZZZ2rdK+VhKHwjWfCQBybuYpvAsyNuQsdqAz+DzolCQJMCNAsprYKt5d3/zZOhIu6ugG2nKiHJk8gag4pMqMV1Jx3jVQ0swBPSAR5eNCrkUqxJsL5oXk1WhdM6h4eK0JfBkqNjZMPcIWcObnTRMEmNtxp+eb0F8FibRC/fx4ocwsob5CGWuM+D87EYcN0Uy7ofNfj5T9lFW3PC2eIKNcVo5G4SsWb8Zwqd4Kfl9dMVIaVfqKXrPM0igmZKGqTMIQmn1ssiC77LV7qKB0tmQTde/wyW1edQ1X7ben8pb9I46A7URsBcgHhw3OWXJiESjss02rMqr4aInS1DGnOv6FHkolFd8TioXcDpPaqx4ijEQzKADGUac+/hhPHPgOO2qg/GO1twGG8ZGsWM022tQRouoVyMt6bUjomX+ML+/6oMDKLeElDkoy5bXlpPn2WIqIkG/whn1gjEa8XRTvY8smKoKYAU="