version: '2'

services:
  mongo:
    image: "mongo:3.6"
    volumes:
      - /data/rsd:/data/db
    command: --bind_ip 0.0.0.0 --smallfiles

  redis:
    image: "redis:alpine"

  celeryworker:
    build:
      context: .
      dockerfile: compose/production/flask/Dockerfile
    env_file:
      - .env
    depends_on:
      - redis
      - mongo
    command: /start-celeryworker.sh

  celerybeat:
    build:
      context: .
      dockerfile: compose/production/flask/Dockerfile
    env_file:
      - .env
    depends_on:
      - celeryworker
    command: /start-celerybeat.sh

  flask:
    build:
      context: .
      dockerfile: compose/production/flask/Dockerfile
    depends_on:
      - celeryworker
    env_file:
      - .env
    command: /start-flask.sh

  nginx:
    build:
      context: .
      dockerfile: compose/production/nginx/Dockerfile
    volumes:
      - /cert:/cert
    depends_on:
      - flask
    env_file:
      - .env
    ports:
      - "443:443"
      - "80:80"
