version: '3'

services:
  admin:
    image: node:14-alpine

  test:
    build:
      context: ./tests
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - auth
      - backend
      - database
      - frontend
      - reverse-proxy
