version: '2'

services:
  redis:
    image: "redis:alpine"

  celeryworker:
    build:
      context: .
      dockerfile: compose/production/flask/Dockerfile
    env_file:
      - .env
    depends_on:
      - redis
    command: /start-celeryworker.sh

  celerybeat:
    build:
      context: .
      dockerfile: compose/production/flask/Dockerfile
    env_file:
      - .env
    depends_on:
      - celeryworker
    command: /start-celerybeat.sh

  flask:
#    container_name: flask
    build:
      context: .
      dockerfile: compose/production/flask/Dockerfile
#    volumes:
#      - .:/app
    depends_on:
      - celeryworker
    env_file:
      - .env
    command: /start-flask.sh

  nginx:
#    container_name: nginx
    build:
      context: .
      dockerfile: compose/production/nginx/Dockerfile
    depends_on:
      - flask
    env_file:
      - .env
    ports:
      - "443:443"
      - "80:80"
