version: '2'

services:
  mongo:
    image: "mongo:3.6"
    volumes:
      - ./db:/data/db
    command: --bind_ip 0.0.0.0
    user: 1000:1000

  flask:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
    env_file:
      - .env.local
    environment:
      - FLASK_APP=/app/entry.py
      - FLASK_DEBUG=1
    command: /start-flask.sh
    ports:
      - "5000:5000"
