name: Integration Tests

on:
  push:
  pull_request:
    types: [opened, reopened]
  schedule:
    - cron:  '0 4 * * *'

jobs:
  tests:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-18.04, ubuntu-latest]

    steps:
      - uses: actions/checkout@v2
      - name: Create the .env file using the example .env file
        run: cp rsd-secrets.env.example .env
      - name: Build images
        run: docker-compose build
      - name: Run tests
        run: docker-compose --file docker-compose.yml --file docker-compose.test.yml run test
