---
name: Linting

on: [push, pull_request]

jobs:
  linting:
    name: Lint the code base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: GitHub Super Linter
        uses: docker://github/super-linter:v3
        env:
          VALIDATE_ALL_CODEBASE: true
          FILTER_REGEX_INCLUDE: admin/.*|auth-github/.*
